begin;

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  description text not null
);

alter table public.courses enable row level security;
grant usage on schema public to anon, authenticated;
revoke all on public.courses from anon, authenticated;
grant select on public.courses to anon, authenticated;
drop policy if exists "Public course catalog" on public.courses;
create policy "Public course catalog" on public.courses
  for select to anon, authenticated using (true);

insert into public.courses (code, title, description) values
  ('CS101', 'Introduction to Programming', 'Learn variables, loops, functions, and problem solving.'),
  ('CS201', 'Data Structures', 'Explore linked lists, stacks, queues, trees, and graphs.'),
  ('MATH201', 'Linear Algebra', 'Study vectors, matrices, linear maps, and eigenvalues.')
on conflict (code) do nothing;

commit;
