begin;

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  description text not null
);

alter table public.courses enable row level security;
grant usage on schema public to anon, authenticated;
revoke all on public.courses from anon, authenticated;
grant select on public.courses to anon, authenticated;
drop policy if exists "Public course catalog" on public.courses;
create policy "Public course catalog" on public.courses
  for select to anon, authenticated using (true);

insert into public.courses (code, title, description) values
  ('HUM101', 'Why Do We Laugh?', 'Examine the social, cultural, and psychological ideas behind laughter and comic timing.'),
  ('HUM201', 'The Craft of Comedy', 'Study setup, surprise, wordplay, parody, and the structure of a memorable joke.'),
  ('HUM301', 'Satire and Social Commentary', 'Analyze how humor can question assumptions, challenge power, and connect audiences across cultures.')
on conflict (code) do nothing;

commit;
